version: "3.9"

services:
  influxdb:
    image: influxdb:2.7
    container_name: apilog-influx
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: admin
      DOCKER_INFLUXDB_INIT_PASSWORD: adminpass
      DOCKER_INFLUXDB_INIT_ORG: apilog
      DOCKER_INFLUXDB_INIT_BUCKET: apilog_raw
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: dev-token
    ports:
      - "8086:8086"
    volumes:
      - influx-data:/var/lib/influxdb2

  api:
    build: ./back/apps/api
    container_name: apilog-api
    environment:
      INFLUX_URL: http://influxdb:8086
      INFLUX_TOKEN: dev-token
      INFLUX_ORG: apilog
      INFLUX_BUCKET: apilog_raw
      CORS_ALLOW_ORIGIN: "*"
    depends_on:
      - influxdb

  nginx:
    build: ./infra/nginx
    container_name: apilog-nginx
    ports:
      - "8080:80"
    depends_on:
      - api
    volumes:
      - ./front/apps/dashboard/dist:/usr/share/nginx/html:ro
      - ./front/apps/collector-js/dist:/usr/share/nginx/html/apilog:ro

volumes:
  influx-data:
